import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const fontBrand = localFont({
	variable: '--font-family-p-p-right-grotesk-mono',
	src: [
		{
			path: '../../public/fonts/PPRightGroteskMono-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-Medium.otf',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-Bold.otf',
			weight: '700',
			style: 'normal',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-RegularItalic.otf',
			weight: '400',
			style: 'italic',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-BoldItalic.otf',
			weight: '700',
			style: 'italic',
		},
	],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={`${fontBrand.variable} h-full antialiased`}>
			<body className='min-h-full flex flex-col'>{children}</body>
		</html>
	)
}
