import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Roboto_Mono } from 'next/font/google'

import { Header } from '@/components/blocks/header/header'

import './globals.css'

const fontBrand = localFont({
	variable: '--font-family-p-p-right-grotesk-mono',
	src: [
		{
			path: '../../public/fonts/PPRightGroteskMono-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-Medium.otf',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-Bold.otf',
			weight: '700',
			style: 'normal',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-RegularItalic.otf',
			weight: '400',
			style: 'italic',
		},
		{
			path: '../../public/fonts/PPRightGroteskMono-BoldItalic.otf',
			weight: '700',
			style: 'italic',
		},
	],
})

const fontPlain = Roboto_Mono({
	variable: '--font-family-roboto-mono',
	subsets: ['latin'],
	weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			data-theme='dark'
			lang='en'
			className={`${fontBrand.variable} ${fontPlain.variable} h-full antialiased`}>
			<body className='flex min-h-full flex-col'>
				<Header />
				{children}
			</body>
		</html>
	)
}
